# Generated by Django 3.0.5 on 2020-04-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('format_name', models.CharField(default='', max_length=100)),
                ('arohanam', models.CharField(max_length=100)),
                ('avarohanam', models.CharField(max_length=100)),
                ('melakarta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='raagaapi.Raga')),
            ],
        ),
    ]
